# Generated by Django 4.1.1 on 2023-05-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_country_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
