# Generated by Django 4.1.1 on 2023-05-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
