# Generated by Django 4.1.1 on 2023-05-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_pharmacyproductprice_product_and_more'),
        ('carts', '0005_cartitem_pharmacy_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pharmacy_product_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacyproductprice'),
        ),
    ]
