# Generated by Django 4.1.1 on 2023-05-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_price'),
        ('pharmacy', '0003_alter_pharmacyproductprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacyproductprice',
            unique_together={('product', 'pharmacy')},
        ),
    ]
